---
- name: Add a new Windows user
  hosts: windows
  vars_prompt:
    - name: username
      prompt: "Username"
      private: no
    - name: passwd
      prompt: "Password"
      private: yes
      confirm: yes
  tasks:
    - name: Add user
      win_user:
        name: '{{ username }}'
        user: '{{ username }}'
        password: '{{ passwd }}'
        groups:
          - Users
        state: present
