---
- name: Add a new Windows user
  hosts: windows
  vars_prompt:
    - name: username
      prompt: "Username"
      secret: no
    - name: passwd
      prompt: "Password"
      secret: yes
      confirm: yes
  tasks:
    - name: Add user
      win_user:
        user: '{{ username }}'
        password: '{{ passwd }}'
        groups:
          - Users
          - Administrators
        state: present
