---
- name: Send a message
  hosts: windows
  vars_prompt:
    - name: message
      prompt: "Message"
      private: no
      confirm: no
  tasks:
    - name: Send message to all users
      win_msg:
        display_seconds: 10
        msg: '{{ message }}'
        wait: yes
