---
- name: Send a toast message
  gather_facts: no
  vars_prompt:
    - name: message
      prompt: "Message"
      default: "Hello red team"
  hosts: windows
  tasks:
     - name: "Send Red Team a message"
       win_toast:
          title: '{{ message }}'
          expire: 45
       async: 60
       poll: 0
