---
- name: Refresh ufw firewall rules with blocked IPs
  hosts: linux
  tasks:
    - name: Block IP
      ufw:
        rule: deny
        from_ip: "{{ item }}"
      with_items: "{{ bad_ips }}"

- name: Refresh windows firewall rules with blocked IPs
  hosts: windows
  tasks:
    - name: Block IP
      win_firewall_rule:
        name: Bad IP
        action: block
        direction: in
        remoteip: "{{ item }}"
      with_items: " {{ bad_ips }}"
