---
- name: Add a new linux user
  hosts: linux
  become: yes
  vars_prompt:
    - name: username
      prompt: "Username"
      secret: no
  tasks:
    - name: Add user
      user:
        name: '{{ username }}'
        shell: /bin/bash
        groups: sudo
      notify: Add key

  handlers:
    - name: Add key
      authorized_key:
        user: '{{ username }}'
        key: "{{ lookup('file', 'keys/id_rsa.pub') }}"
        state: present
