---
- name: Remove a kernel module
  hosts: linux
  become: true
  vars_prompt:
    - name: module
      prompt: "Module name"
  tasks:
    - name: Remove the kernel module
      modprobe:
        name: '{{ module }}'
        state: absent
