---
- name: Remove a user
  hosts: linux
  become: yes
  vars_prompt:
    - name: username
      prompt: "Username"
      confirm: yes
      secret: no
  tasks:
    - name: Remove the user account
    user:
      name: "{{ username }}"
      state: absent
      remove: yes
